/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 03:40:26 GMT 2017
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.Node;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Node_ESTest extends Node_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer((-2680));
      Node<Integer> node0 = new Node<Integer>(integer0);
      node0.setNext((Node<Integer>) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Node<Integer> node0 = new Node<Integer>((Integer) null);
      Integer integer0 = node0.getObject();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Node<Integer> node0 = new Node<Integer>((Integer) null);
      node0.setNext(node0);
      Node<Integer> node1 = node0.getNext();
      assertSame(node0, node1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Integer integer0 = new Integer((-2680));
      Node<Integer> node0 = new Node<Integer>(integer0);
      Integer integer1 = node0.getObject();
      assertEquals((-2680), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Node<Integer> node0 = new Node<Integer>((Integer) null);
      Node<Integer> node1 = node0.getNext();
      assertNull(node1);
  }
}
